### ISSUE TITLE
Error while building the code

### ISSUE THREAD

**Issue by Saudibyte** [PMaynard/ICS-TestBed-Framework#4]
Hi,
While building the code using "mvn clean package" I got the following error. Is this a known issue? What is the solution?

mvn clean package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/lab/Downloads/ICS-TestBed-Framework-master/UA-Java/pom.xml of /home/lab/Downloads/ICS-TestBed-Framework-master/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project xyz.scada.testbed:testbed:1.0 (/home/lab/Downloads/ICS-TestBed-Framework-master/pom.xml) has 1 error
[ERROR]     Child module /home/lab/Downloads/ICS-TestBed-Framework-master/UA-Java/pom.xml of /home/lab/Downloads/ICS-TestBed-Framework-master/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by 11235yuan** [comment]
What a coincidence! 
I have the same problem. 
Have you found a solution?

**Comment by 11235yuan** [comment]
我已经找到解决方案了。首先UA-Java 里面 是空的，需要 git clone这个https://github.com/OPCFoundation/UA-Java-Legacy 链接到UA-Java 下，；
后面还会遇到 
[INFO] Running org.openmuc.j60870.CP56Time2aTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in org.openmuc.j60870.CP56Time2aTest
[ERROR] testTimestampToCalendar(org.openmuc.j60870.CP56Time2aTest)  Time elapsed: 0.011 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [3]; expected:<15> but was:<23>
	at org.openmuc.j60870.CP56Time2aTest.testTimestampToCalendar(CP56Time2aTest.java:35)
Caused by: java.lang.AssertionError: expected:<15> but was:<23>
	at org.openmuc.j60870.CP56Time2aTest.testTimestampToCalendar(CP56Time2aTest.java:35)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CP56Time2aTest.testTimestampToCalendar:35 arrays first differed at element [3]; expected:<15> but was:<23>
[INFO] 
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
这个问题，然后需要打开文件
ICS-Scada-Virtual-TestBed/j60870/src/test/java/org/openmuc/j60870/CP56Time2aTest.java
修改文件第35行，数组的第4个值，为 23 的（expected:<15> but was:<23>）十六进制值。
然后就会遇到新的问题，Amazing，，，
